import libssh2

proc getErrorName*(rc: int): string =
  case rc:
  of LIBSSH2_INVALID_SOCKET: "LIBSSH2_INVALID_SOCKET" # -1
  of LIBSSH2_DH_GEX_MINGROUP: "LIBSSH2_DH_GEX_MINGROUP" # 1024
  of LIBSSH2_DH_GEX_OPTGROUP: "LIBSSH2_DH_GEX_OPTGROUP" # 1536
  of LIBSSH2_DH_GEX_MAXGROUP: "LIBSSH2_DH_GEX_MAXGROUP" # 2048
  of LIBSSH2_TERM_WIDTH: "LIBSSH2_TERM_WIDTH" # 80
  of LIBSSH2_TERM_HEIGHT: "LIBSSH2_TERM_HEIGHT" # 24
  of LIBSSH2_TERM_WIDTH_PX: "LIBSSH2_TERM_WIDTH_PX" # 0
  # of LIBSSH2_TERM_HEIGHT_PX: "LIBSSH2_TERM_HEIGHT_PX" # 0
  of LIBSSH2_SOCKET_POLL_UDELAY: "LIBSSH2_SOCKET_POLL_UDELAY" # 250000
  of LIBSSH2_SOCKET_POLL_MAXLOOPS: "LIBSSH2_SOCKET_POLL_MAXLOOPS" # 120
  of LIBSSH2_PACKET_MAXCOMP: "LIBSSH2_PACKET_MAXCOMP" # 32000
  # of LIBSSH2_PACKET_MAXDECOMP: "LIBSSH2_PACKET_MAXDECOMP" # 40000
  of LIBSSH2_PACKET_MAXPAYLOAD: "LIBSSH2_PACKET_MAXPAYLOAD" # 40000
  # of LIBSSH2_CALLBACK_IGNORE: "LIBSSH2_CALLBACK_IGNORE" # 0
  of LIBSSH2_CALLBACK_DEBUG: "LIBSSH2_CALLBACK_DEBUG" # 1
  of LIBSSH2_CALLBACK_DISCONNECT: "LIBSSH2_CALLBACK_DISCONNECT" # 2
  of LIBSSH2_CALLBACK_MACERROR: "LIBSSH2_CALLBACK_MACERROR" # 3
  of LIBSSH2_CALLBACK_X11: "LIBSSH2_CALLBACK_X11" # 4
  of LIBSSH2_CALLBACK_SEND: "LIBSSH2_CALLBACK_SEND" # 5
  of LIBSSH2_CALLBACK_RECV: "LIBSSH2_CALLBACK_RECV" # 6
  # of LIBSSH2_METHOD_KEX: "LIBSSH2_METHOD_KEX" # 0
  # of LIBSSH2_METHOD_HOSTKEY: "LIBSSH2_METHOD_HOSTKEY" # 1
  # of LIBSSH2_METHOD_CRYPT_CS: "LIBSSH2_METHOD_CRYPT_CS" # 2
  # of LIBSSH2_METHOD_CRYPT_SC: "LIBSSH2_METHOD_CRYPT_SC" # 3
  # of LIBSSH2_METHOD_MAC_CS: "LIBSSH2_METHOD_MAC_CS" # 4
  # of LIBSSH2_METHOD_MAC_SC: "LIBSSH2_METHOD_MAC_SC" # 5
  # of LIBSSH2_METHOD_COMP_CS: "LIBSSH2_METHOD_COMP_CS" # 6
  of LIBSSH2_METHOD_COMP_SC: "LIBSSH2_METHOD_COMP_SC" # 7
  of LIBSSH2_METHOD_LANG_CS: "LIBSSH2_METHOD_LANG_CS" # 8
  of LIBSSH2_METHOD_LANG_SC: "LIBSSH2_METHOD_LANG_SC" # 9
  # of LIBSSH2_FLAG_SIGPIPE: "LIBSSH2_FLAG_SIGPIPE" # 1
  # of LIBSSH2_FLAG_COMPRESS: "LIBSSH2_FLAG_COMPRESS" # 2
  # of LIBSSH2_POLLFD_SOCKET: "LIBSSH2_POLLFD_SOCKET" # 1
  # of LIBSSH2_POLLFD_CHANNEL: "LIBSSH2_POLLFD_CHANNEL" # 2
  # of LIBSSH2_POLLFD_LISTENER: "LIBSSH2_POLLFD_LISTENER" # 3
  # of LIBSSH2_POLLFD_POLLIN: "LIBSSH2_POLLFD_POLLIN" # 0x0001
  # of LIBSSH2_POLLFD_POLLPRI: "LIBSSH2_POLLFD_POLLPRI" # 0x0002
  # of LIBSSH2_POLLFD_POLLEXT: "LIBSSH2_POLLFD_POLLEXT" # 0x0002
  # of LIBSSH2_POLLFD_POLLOUT: "LIBSSH2_POLLFD_POLLOUT" # 0x0004
  # of LIBSSH2_POLLFD_POLLERR: "LIBSSH2_POLLFD_POLLERR" # 0x0008
  of LIBSSH2_POLLFD_POLLHUP: "LIBSSH2_POLLFD_POLLHUP" # 0x0010
  # of LIBSSH2_POLLFD_SESSION_CLOSED: "LIBSSH2_POLLFD_SESSION_CLOSED" # 0x0010
  of LIBSSH2_POLLFD_POLLNVAL: "LIBSSH2_POLLFD_POLLNVAL" # 0x0020
  of LIBSSH2_POLLFD_POLLEX: "LIBSSH2_POLLFD_POLLEX" # 0x0040
  # of LIBSSH2_POLLFD_CHANNEL_CLOSED: "LIBSSH2_POLLFD_CHANNEL_CLOSED" # 0x0080
  # of LIBSSH2_POLLFD_LISTENER_CLOSED: "LIBSSH2_POLLFD_LISTENER_CLOSED" # 0x0080
  # of LIBSSH2_SESSION_BLOCK_INBOUND: "LIBSSH2_SESSION_BLOCK_INBOUND" # 0x0001
  # of LIBSSH2_SESSION_BLOCK_OUTBOUND: "LIBSSH2_SESSION_BLOCK_OUTBOUND" # 0x0002
  # of LIBSSH2_HOSTKEY_HASH_MD5: "LIBSSH2_HOSTKEY_HASH_MD5" # 1
  # of LIBSSH2_HOSTKEY_HASH_SHA1: "LIBSSH2_HOSTKEY_HASH_SHA1" # 2
  # of LIBSSH2_HOSTKEY_TYPE_UNKNOWN: "LIBSSH2_HOSTKEY_TYPE_UNKNOWN" # 0
  # of LIBSSH2_HOSTKEY_TYPE_RSA: "LIBSSH2_HOSTKEY_TYPE_RSA" # 1
  # of LIBSSH2_HOSTKEY_TYPE_DSS: "LIBSSH2_HOSTKEY_TYPE_DSS" # 2
  # of LIBSSH2_ERROR_NONE: "LIBSSH2_ERROR_NONE" # 0
  # of LIBSSH2_ERROR_SOCKET_NONE: "LIBSSH2_ERROR_SOCKET_NONE" # -1
  of LIBSSH2_ERROR_BANNER_RECV: "LIBSSH2_ERROR_BANNER_RECV" # -2
  of LIBSSH2_ERROR_BANNER_SEND: "LIBSSH2_ERROR_BANNER_SEND" # -3
  of LIBSSH2_ERROR_INVALID_MAC: "LIBSSH2_ERROR_INVALID_MAC" # -4
  of LIBSSH2_ERROR_KEX_FAILURE: "LIBSSH2_ERROR_KEX_FAILURE" # -5
  of LIBSSH2_ERROR_ALLOC: "LIBSSH2_ERROR_ALLOC" # -6
  of LIBSSH2_ERROR_SOCKET_SEND: "LIBSSH2_ERROR_SOCKET_SEND" # -7
  of LIBSSH2_ERROR_KEY_EXCHANGE_FAILURE: "LIBSSH2_ERROR_KEY_EXCHANGE_FAILURE" # -8
  of LIBSSH2_ERROR_TIMEOUT: "LIBSSH2_ERROR_TIMEOUT" # -9
  of LIBSSH2_ERROR_HOSTKEY_INIT: "LIBSSH2_ERROR_HOSTKEY_INIT" # -10
  of LIBSSH2_ERROR_HOSTKEY_SIGN: "LIBSSH2_ERROR_HOSTKEY_SIGN" # -11
  of LIBSSH2_ERROR_DECRYPT: "LIBSSH2_ERROR_DECRYPT" # -12
  of LIBSSH2_ERROR_SOCKET_DISCONNECT: "LIBSSH2_ERROR_SOCKET_DISCONNECT" # -13
  of LIBSSH2_ERROR_PROTO: "LIBSSH2_ERROR_PROTO" # -14
  of LIBSSH2_ERROR_PASSWORD_EXPIRED: "LIBSSH2_ERROR_PASSWORD_EXPIRED" # -15
  of LIBSSH2_ERROR_FILE: "LIBSSH2_ERROR_FILE" # -16
  of LIBSSH2_ERROR_METHOD_NONE: "LIBSSH2_ERROR_METHOD_NONE" # -17
  of LIBSSH2_ERROR_AUTHENTICATION_FAILED: "LIBSSH2_ERROR_AUTHENTICATION_FAILED" # -18
  # of LIBSSH2_ERROR_PUBLICKEY_UNRECOGNIZED: "LIBSSH2_ERROR_PUBLICKEY_UNRECOGNIZED" # LIBSSH2_ERROR_AUTHENTICATION_FAILED
  of LIBSSH2_ERROR_PUBLICKEY_UNVERIFIED: "LIBSSH2_ERROR_PUBLICKEY_UNVERIFIED" # -19
  of LIBSSH2_ERROR_CHANNEL_OUTOFORDER: "LIBSSH2_ERROR_CHANNEL_OUTOFORDER" # -20
  of LIBSSH2_ERROR_CHANNEL_FAILURE: "LIBSSH2_ERROR_CHANNEL_FAILURE" # -21
  of LIBSSH2_ERROR_CHANNEL_REQUEST_DENIED: "LIBSSH2_ERROR_CHANNEL_REQUEST_DENIED" # -22
  of LIBSSH2_ERROR_CHANNEL_UNKNOWN: "LIBSSH2_ERROR_CHANNEL_UNKNOWN" # -23
  of LIBSSH2_ERROR_CHANNEL_WINDOW_EXCEEDED: "LIBSSH2_ERROR_CHANNEL_WINDOW_EXCEEDED" # -24
  of LIBSSH2_ERROR_CHANNEL_PACKET_EXCEEDED: "LIBSSH2_ERROR_CHANNEL_PACKET_EXCEEDED" # -25
  of LIBSSH2_ERROR_CHANNEL_CLOSED: "LIBSSH2_ERROR_CHANNEL_CLOSED" # -26
  of LIBSSH2_ERROR_CHANNEL_EOF_SENT: "LIBSSH2_ERROR_CHANNEL_EOF_SENT" # -27
  of LIBSSH2_ERROR_SCP_PROTOCOL: "LIBSSH2_ERROR_SCP_PROTOCOL" # -28
  of LIBSSH2_ERROR_ZLIB: "LIBSSH2_ERROR_ZLIB" # -29
  of LIBSSH2_ERROR_SOCKET_TIMEOUT: "LIBSSH2_ERROR_SOCKET_TIMEOUT" # -30
  of LIBSSH2_ERROR_SFTP_PROTOCOL: "LIBSSH2_ERROR_SFTP_PROTOCOL" # -31
  of LIBSSH2_ERROR_REQUEST_DENIED: "LIBSSH2_ERROR_REQUEST_DENIED" # -32
  of LIBSSH2_ERROR_METHOD_NOT_SUPPORTED: "LIBSSH2_ERROR_METHOD_NOT_SUPPORTED" # -33
  of LIBSSH2_ERROR_INVAL: "LIBSSH2_ERROR_INVAL" # -34
  of LIBSSH2_ERROR_INVALID_POLL_TYPE: "LIBSSH2_ERROR_INVALID_POLL_TYPE" # -35
  of LIBSSH2_ERROR_PUBLICKEY_PROTOCOL: "LIBSSH2_ERROR_PUBLICKEY_PROTOCOL" # -36
  of LIBSSH2_ERROR_EAGAIN: "LIBSSH2_ERROR_EAGAIN" # -37
  of LIBSSH2_ERROR_BUFFER_TOO_SMALL: "LIBSSH2_ERROR_BUFFER_TOO_SMALL" # -38
  of LIBSSH2_ERROR_BAD_USE: "LIBSSH2_ERROR_BAD_USE" # -39
  of LIBSSH2_ERROR_COMPRESS: "LIBSSH2_ERROR_COMPRESS" # -40
  of LIBSSH2_ERROR_OUT_OF_BOUNDARY: "LIBSSH2_ERROR_OUT_OF_BOUNDARY" # -41
  of LIBSSH2_ERROR_AGENT_PROTOCOL: "LIBSSH2_ERROR_AGENT_PROTOCOL" # -42
  of LIBSSH2_ERROR_SOCKET_RECV: "LIBSSH2_ERROR_SOCKET_RECV" # -43
  of LIBSSH2_ERROR_ENCRYPT: "LIBSSH2_ERROR_ENCRYPT" # -44
  of LIBSSH2_ERROR_BAD_SOCKET: "LIBSSH2_ERROR_BAD_SOCKET" # -45
  of LIBSSH2_ERROR_KNOWN_HOSTS: "LIBSSH2_ERROR_KNOWN_HOSTS" # -46
  # of LIBSSH2_ERROR_BANNER_NONE: "LIBSSH2_ERROR_BANNER_NONE" # LIBSSH2_ERROR_BANNER_RECV
  # of LIBSSH2_INIT_NO_CRYPTO: "LIBSSH2_INIT_NO_CRYPTO" # 0x0001
  # of LIBSSH2_CHANNEL_WINDOW_DEFAULT: "LIBSSH2_CHANNEL_WINDOW_DEFAULT" # (2*1024*1024)
  # of LIBSSH2_CHANNEL_PACKET_DEFAULT: "LIBSSH2_CHANNEL_PACKET_DEFAULT" # 32768
  # of LIBSSH2_CHANNEL_MINADJUST: "LIBSSH2_CHANNEL_MINADJUST" # 1024
  # of LIBSSH2_CHANNEL_EXTENDED_DATA_NORMAL: "LIBSSH2_CHANNEL_EXTENDED_DATA_NORMAL" # 0
  # of LIBSSH2_CHANNEL_EXTENDED_DATA_IGNORE: "LIBSSH2_CHANNEL_EXTENDED_DATA_IGNORE" # 1
  # of LIBSSH2_CHANNEL_EXTENDED_DATA_MERGE: "LIBSSH2_CHANNEL_EXTENDED_DATA_MERGE" # 2
  # of LIBSSH2CHANNEL_EAGAIN: "LIBSSH2CHANNEL_EAGAIN" # LIBSSH2_ERROR_EAGAIN
  # of LIBSSH2_CHANNEL_FLUSH_EXTENDED_DATA: "LIBSSH2_CHANNEL_FLUSH_EXTENDED_DATA" # -1
  # of LIBSSH2_CHANNEL_FLUSH_ALL: "LIBSSH2_CHANNEL_FLUSH_ALL" # -2
  # of LIBSSH2_KNOWNHOST_TYPE_MASK: "LIBSSH2_KNOWNHOST_TYPE_MASK" # 0xffff
  # of LIBSSH2_KNOWNHOST_TYPE_PLAIN: "LIBSSH2_KNOWNHOST_TYPE_PLAIN" # 1
  # of LIBSSH2_KNOWNHOST_TYPE_SHA1: "LIBSSH2_KNOWNHOST_TYPE_SHA1" # 2
  # of LIBSSH2_KNOWNHOST_TYPE_CUSTOM: "LIBSSH2_KNOWNHOST_TYPE_CUSTOM" # 3
  # of LIBSSH2_KNOWNHOST_KEYENC_MASK: "LIBSSH2_KNOWNHOST_KEYENC_MASK" # (3 shl 16)
  # of LIBSSH2_KNOWNHOST_KEYENC_RAW: "LIBSSH2_KNOWNHOST_KEYENC_RAW" # (1 shl 16)
  # of LIBSSH2_KNOWNHOST_KEYENC_BASE64: "LIBSSH2_KNOWNHOST_KEYENC_BASE64" # (2 shl 16)
  # of LIBSSH2_KNOWNHOST_KEY_MASK: "LIBSSH2_KNOWNHOST_KEY_MASK" # (7 shl 18)
  # of LIBSSH2_KNOWNHOST_KEY_SHIFT: "LIBSSH2_KNOWNHOST_KEY_SHIFT" # 18
  # of LIBSSH2_KNOWNHOST_KEY_RSA1: "LIBSSH2_KNOWNHOST_KEY_RSA1" # (1 shl 18)
  # of LIBSSH2_KNOWNHOST_KEY_SSHRSA: "LIBSSH2_KNOWNHOST_KEY_SSHRSA" # (2 shl 18)
  # of LIBSSH2_KNOWNHOST_KEY_SSHDSS: "LIBSSH2_KNOWNHOST_KEY_SSHDSS" # (3 shl 18)
  # of LIBSSH2_KNOWNHOST_KEY_UNKNOWN: "LIBSSH2_KNOWNHOST_KEY_UNKNOWN" # (7 shl 18)
  # of LIBSSH2_KNOWNHOST_CHECK_MATCH: "LIBSSH2_KNOWNHOST_CHECK_MATCH" # 0
  # of LIBSSH2_KNOWNHOST_CHECK_MISMATCH: "LIBSSH2_KNOWNHOST_CHECK_MISMATCH" # 1
  # of LIBSSH2_KNOWNHOST_CHECK_NOTFOUND: "LIBSSH2_KNOWNHOST_CHECK_NOTFOUND" # 2
  # of LIBSSH2_KNOWNHOST_CHECK_FAILURE: "LIBSSH2_KNOWNHOST_CHECK_FAILURE" # 3
  # of LIBSSH2_KNOWNHOST_FILE_OPENSSH: "LIBSSH2_KNOWNHOST_FILE_OPENSSH" # 1
  # of LIBSSH2_TRACE_TRANS: "LIBSSH2_TRACE_TRANS" # (1 shl 1)
  # of LIBSSH2_TRACE_KEX: "LIBSSH2_TRACE_KEX" # (1 shl 2)
  # of LIBSSH2_TRACE_AUTH: "LIBSSH2_TRACE_AUTH" # (1 shl 3)
  # of LIBSSH2_TRACE_CONN: "LIBSSH2_TRACE_CONN" # (1 shl 4)
  # of LIBSSH2_TRACE_SCP: "LIBSSH2_TRACE_SCP" # (1 shl 5)
  # of LIBSSH2_TRACE_SFTP: "LIBSSH2_TRACE_SFTP" # (1 shl 6)
  # of LIBSSH2_TRACE_ERROR: "LIBSSH2_TRACE_ERROR" # (1 shl 7)
  # of LIBSSH2_TRACE_PUBLICKEY: "LIBSSH2_TRACE_PUBLICKEY" # (1 shl 8)
  # of LIBSSH2_TRACE_SOCKET: "LIBSSH2_TRACE_SOCKET" # (1 shl 9)
  # of LIBSSH2_SFTP_OPENFILE: "LIBSSH2_SFTP_OPENFILE" # 0
  # of LIBSSH2_SFTP_OPENDIR: "LIBSSH2_SFTP_OPENDIR" # 1
  # of LIBSSH2_SFTP_RENAME_OVERWRITE: "LIBSSH2_SFTP_RENAME_OVERWRITE" # 0x00000001
  # of LIBSSH2_SFTP_RENAME_ATOMIC: "LIBSSH2_SFTP_RENAME_ATOMIC" # 0x00000002
  # of LIBSSH2_SFTP_RENAME_NATIVE: "LIBSSH2_SFTP_RENAME_NATIVE" # 0x00000004
  # of LIBSSH2_SFTP_STAT: "LIBSSH2_SFTP_STAT" # 0
  # of LIBSSH2_SFTP_LSTAT: "LIBSSH2_SFTP_LSTAT" # 1
  # of LIBSSH2_SFTP_SETSTAT: "LIBSSH2_SFTP_SETSTAT" # 2
  # of LIBSSH2_SFTP_SYMLINK: "LIBSSH2_SFTP_SYMLINK" # 0
  # of LIBSSH2_SFTP_READLINK: "LIBSSH2_SFTP_READLINK" # 1
  # of LIBSSH2_SFTP_REALPATH: "LIBSSH2_SFTP_REALPATH" # 2
  # of LIBSSH2_SFTP_ATTR_SIZE: "LIBSSH2_SFTP_ATTR_SIZE" # 0x00000001
  # of LIBSSH2_SFTP_ATTR_UIDGID: "LIBSSH2_SFTP_ATTR_UIDGID" # 0x00000002
  # of LIBSSH2_SFTP_ATTR_PERMISSIONS: "LIBSSH2_SFTP_ATTR_PERMISSIONS" # 0x00000004
  # of LIBSSH2_SFTP_ATTR_ACMODTIME: "LIBSSH2_SFTP_ATTR_ACMODTIME" # 0x00000008
  # of LIBSSH2_SFTP_ATTR_EXTENDED: "LIBSSH2_SFTP_ATTR_EXTENDED" # 0x80000000
  # of LIBSSH2_SFTP_ST_RDONLY: "LIBSSH2_SFTP_ST_RDONLY" # 0x00000001
  # of LIBSSH2_SFTP_ST_NOSUID: "LIBSSH2_SFTP_ST_NOSUID" # 0x00000002
  # of LIBSSH2_SFTP_TYPE_REGULAR: "LIBSSH2_SFTP_TYPE_REGULAR" # 1
  # of LIBSSH2_SFTP_TYPE_DIRECTORY: "LIBSSH2_SFTP_TYPE_DIRECTORY" # 2
  # of LIBSSH2_SFTP_TYPE_SYMLINK: "LIBSSH2_SFTP_TYPE_SYMLINK" # 3
  # of LIBSSH2_SFTP_TYPE_SPECIAL: "LIBSSH2_SFTP_TYPE_SPECIAL" # 4
  # of LIBSSH2_SFTP_TYPE_UNKNOWN: "LIBSSH2_SFTP_TYPE_UNKNOWN" # 5
  # of LIBSSH2_SFTP_TYPE_SOCKET: "LIBSSH2_SFTP_TYPE_SOCKET" # 6
  # of LIBSSH2_SFTP_TYPE_CHAR_DEVICE: "LIBSSH2_SFTP_TYPE_CHAR_DEVICE" # 7
  # of LIBSSH2_SFTP_TYPE_BLOCK_DEVICE: "LIBSSH2_SFTP_TYPE_BLOCK_DEVICE" # 8
  # of LIBSSH2_SFTP_TYPE_FIFO: "LIBSSH2_SFTP_TYPE_FIFO" # 9
  # of LIBSSH2_SFTP_S_IFMT: "LIBSSH2_SFTP_S_IFMT" # 0170000
  # of LIBSSH2_SFTP_S_IFIFO: "LIBSSH2_SFTP_S_IFIFO" # 0010000
  # of LIBSSH2_SFTP_S_IFCHR: "LIBSSH2_SFTP_S_IFCHR" # 0020000
  # of LIBSSH2_SFTP_S_IFDIR: "LIBSSH2_SFTP_S_IFDIR" # 0040000
  # of LIBSSH2_SFTP_S_IFBLK: "LIBSSH2_SFTP_S_IFBLK" # 0060000
  # of LIBSSH2_SFTP_S_IFREG: "LIBSSH2_SFTP_S_IFREG" # 0100000
  # of LIBSSH2_SFTP_S_IFLNK: "LIBSSH2_SFTP_S_IFLNK" # 0120000
  # of LIBSSH2_SFTP_S_IFSOCK: "LIBSSH2_SFTP_S_IFSOCK" # 0140000
  # of LIBSSH2_SFTP_S_IRWXU: "LIBSSH2_SFTP_S_IRWXU" # 0000700
  # of LIBSSH2_SFTP_S_IRUSR: "LIBSSH2_SFTP_S_IRUSR" # 0000400
  # of LIBSSH2_SFTP_S_IWUSR: "LIBSSH2_SFTP_S_IWUSR" # 0000200
  # of LIBSSH2_SFTP_S_IXUSR: "LIBSSH2_SFTP_S_IXUSR" # 0000100
  # of LIBSSH2_SFTP_S_IRWXG: "LIBSSH2_SFTP_S_IRWXG" # 0000070
  # of LIBSSH2_SFTP_S_IRGRP: "LIBSSH2_SFTP_S_IRGRP" # 0000040
  # of LIBSSH2_SFTP_S_IWGRP: "LIBSSH2_SFTP_S_IWGRP" # 0000020
  # of LIBSSH2_SFTP_S_IXGRP: "LIBSSH2_SFTP_S_IXGRP" # 0000010
  # of LIBSSH2_SFTP_S_IRWXO: "LIBSSH2_SFTP_S_IRWXO" # 0000007
  # of LIBSSH2_SFTP_S_IROTH: "LIBSSH2_SFTP_S_IROTH" # 0000004
  # of LIBSSH2_SFTP_S_IWOTH: "LIBSSH2_SFTP_S_IWOTH" # 0000002
  # of LIBSSH2_SFTP_S_IXOTH: "LIBSSH2_SFTP_S_IXOTH" # 0000001
  # of LIBSSH2_FXF_READ: "LIBSSH2_FXF_READ" # 0x00000001
  # of LIBSSH2_FXF_WRITE: "LIBSSH2_FXF_WRITE" # 0x00000002
  # of LIBSSH2_FXF_APPEND: "LIBSSH2_FXF_APPEND" # 0x00000004
  # of LIBSSH2_FXF_CREAT: "LIBSSH2_FXF_CREAT" # 0x00000008
  # of LIBSSH2_FXF_TRUNC: "LIBSSH2_FXF_TRUNC" # 0x00000010
  # of LIBSSH2_FXF_EXCL: "LIBSSH2_FXF_EXCL" # 0x00000020
  # of LIBSSH2SFTP_EAGAIN: "LIBSSH2SFTP_EAGAIN" # LIBSSH2_ERROR_EAGAIN


  # of SSH_DISCONNECT_HOST_NOT_ALLOWED_TO_CONNECT: "SSH_DISCONNECT_HOST_NOT_ALLOWED_TO_CONNECT" # 1
  # of SSH_DISCONNECT_PROTOCOL_ERROR: "SSH_DISCONNECT_PROTOCOL_ERROR" # 2
  # of SSH_DISCONNECT_KEY_EXCHANGE_FAILED: "SSH_DISCONNECT_KEY_EXCHANGE_FAILED" # 3
  # of SSH_DISCONNECT_RESERVED: "SSH_DISCONNECT_RESERVED" # 4
  # of SSH_DISCONNECT_MAC_ERROR: "SSH_DISCONNECT_MAC_ERROR" # 5
  # of SSH_DISCONNECT_COMPRESSION_ERROR: "SSH_DISCONNECT_COMPRESSION_ERROR" # 6
  # of SSH_DISCONNECT_SERVICE_NOT_AVAILABLE: "SSH_DISCONNECT_SERVICE_NOT_AVAILABLE" # 7
  # of SSH_DISCONNECT_PROTOCOL_VERSION_NOT_SUPPORTED: "SSH_DISCONNECT_PROTOCOL_VERSION_NOT_SUPPORTED" # 8
  # of SSH_DISCONNECT_HOST_KEY_NOT_VERIFIABLE: "SSH_DISCONNECT_HOST_KEY_NOT_VERIFIABLE" # 9
  # of SSH_DISCONNECT_CONNECTION_LOST: "SSH_DISCONNECT_CONNECTION_LOST" # 10
  # of SSH_DISCONNECT_BY_APPLICATION: "SSH_DISCONNECT_BY_APPLICATION" # 11
  # of SSH_DISCONNECT_TOO_MANY_CONNECTIONS: "SSH_DISCONNECT_TOO_MANY_CONNECTIONS" # 12
  # of SSH_DISCONNECT_AUTH_CANCELLED_BY_USER: "SSH_DISCONNECT_AUTH_CANCELLED_BY_USER" # 13
  # of SSH_DISCONNECT_NO_MORE_AUTH_METHODS_AVAILABLE: "SSH_DISCONNECT_NO_MORE_AUTH_METHODS_AVAILABLE" # 14
  # of SSH_DISCONNECT_ILLEGAL_USER_NAME: "SSH_DISCONNECT_ILLEGAL_USER_NAME" # 15
  # of SSH_EXTENDED_DATA_STDERR: "SSH_EXTENDED_DATA_STDERR" # 1
  else:
    raise newException(AssertionError, "No such error code: " & $rc)

proc getSftpErrorName*(rc: int): string =
  case rc:
  of LIBSSH2_FX_OK: "LIBSSH2_FX_OK" # 0
  of LIBSSH2_FX_EOF: "LIBSSH2_FX_EOF" # 1
  of LIBSSH2_FX_NO_SUCH_FILE: "LIBSSH2_FX_NO_SUCH_FILE" # 2
  of LIBSSH2_FX_PERMISSION_DENIED: "LIBSSH2_FX_PERMISSION_DENIED" # 3
  of LIBSSH2_FX_FAILURE: "LIBSSH2_FX_FAILURE" # 4
  of LIBSSH2_FX_BAD_MESSAGE: "LIBSSH2_FX_BAD_MESSAGE" # 5
  of LIBSSH2_FX_NO_CONNECTION: "LIBSSH2_FX_NO_CONNECTION" # 6
  of LIBSSH2_FX_CONNECTION_LOST: "LIBSSH2_FX_CONNECTION_LOST" # 7
  of LIBSSH2_FX_OP_UNSUPPORTED: "LIBSSH2_FX_OP_UNSUPPORTED" # 8
  of LIBSSH2_FX_INVALID_HANDLE: "LIBSSH2_FX_INVALID_HANDLE" # 9
  of LIBSSH2_FX_NO_SUCH_PATH: "LIBSSH2_FX_NO_SUCH_PATH" # 10
  of LIBSSH2_FX_FILE_ALREADY_EXISTS: "LIBSSH2_FX_FILE_ALREADY_EXISTS" # 11
  of LIBSSH2_FX_WRITE_PROTECT: "LIBSSH2_FX_WRITE_PROTECT" # 12
  of LIBSSH2_FX_NO_MEDIA: "LIBSSH2_FX_NO_MEDIA" # 13
  of LIBSSH2_FX_NO_SPACE_ON_FILESYSTEM: "LIBSSH2_FX_NO_SPACE_ON_FILESYSTEM" # 14
  of LIBSSH2_FX_QUOTA_EXCEEDED: "LIBSSH2_FX_QUOTA_EXCEEDED" # 15
  # of LIBSSH2_FX_UNKNOWN_PRINCIPLE: "LIBSSH2_FX_UNKNOWN_PRINCIPLE" # 16
  of LIBSSH2_FX_UNKNOWN_PRINCIPAL: "LIBSSH2_FX_UNKNOWN_PRINCIPAL" # 16
  of LIBSSH2_FX_LOCK_CONFlICT: "LIBSSH2_FX_LOCK_CONFlICT" # 17
  of LIBSSH2_FX_DIR_NOT_EMPTY: "LIBSSH2_FX_DIR_NOT_EMPTY" # 18
  of LIBSSH2_FX_NOT_A_DIRECTORY: "LIBSSH2_FX_NOT_A_DIRECTORY" # 19
  of LIBSSH2_FX_INVALID_FILENAME: "LIBSSH2_FX_INVALID_FILENAME" # 20
  of LIBSSH2_FX_LINK_LOOP: "LIBSSH2_FX_LINK_LOOP" # 21
  else:
    raise newException(
      AssertionError,
      "Not such SFTP error return code: " & $rc
    )
